### ISSUE TITLE
No skyline library generated

### ISSUE THREAD

**Issue by LKittinun** [vdemichev/DiaNN#1052]
First of all, congratulations on the new version!
After I finished a run with MBR, this message appeared when I tried to click on skyline visualization.

![image](https://github.com/vdemichev/DiaNN/assets/63741805/bc2d7749-f4ff-4fe9-9843-bb75db85a132)

There is also no file that it asked for. I am not sure what the cause is. The first time I ran this, it worked as intended. (This is the second run, a new experiment.)

Here's the log file of the run

[report.log.txt](https://github.com/user-attachments/files/15847905/report.log.txt)

Additional information: After I try to change some settings, it seems that if I remove the "Deep learning-based spectra, RT, and IM prediction" tick, the skyline library generated as usual. I am not sure if this is intended.

Regards,
Pete

**Comment by vdemichev** [comment]
Hi Pete,

Thank you for spotting this, indeed it's because the predictor is activated (I just haven't thought about this possibility; if you already have a predicted library, normally you would not want to keep it active (just wastes time), unless in certain scenarious with plexDIA) - the fix is easy and will be included in the next release update.

Best,
Vadim

**Comment by LKittinun** [comment]
Thank you very much for your efforts, Vadim. I greatly appreciate your software!

Regards,
Pete
