### ISSUE TITLE
Variations in Predicted Spectral Libraries Using Different DIANN Versions

### ISSUE THREAD

**Issue by rolivella** [vdemichev/DiaNN#1179]
Hello,

We are wondering whether using different versions of **DIANN** (while keeping the same FASTA file) could result in differences in the predicted spectral libraries. Specifically, could changes between versions affect the spectral predictions or introduce discrepancies in any other way?

It would be helpful to know if anyone has experienced variations in library generation across versions and if there are recommended practices to ensure consistency when upgrading DIANN.

Thanks in advance for your insights!

**Comment by vdemichev** [comment]
Hi Roger,

Yes, predicted libs can be different between different versions. However 1.9 and 1.9.1, for example, have an identical predictor. 

But when you are 100% guaranteed to see a variation, is when running on CPUs supporting different vector instruction sets. This happens because the Pytorch library used by DIA-NN automatically uses vector instructions when available (for higher speed), and this leads to different code used by Pytorch internally, which can result in different output due to limited precision of real-number calculations. This is the reason why DIA-NN prints CPU info at the top of the log on Windows, to record the instruction set used. 

Best,
Vadim

**Comment by rolivella** [comment]
Thank you very much for this nice answer!
