### ISSUE TITLE
SILAC Channel Decoy

### ISSUE THREAD

**Issue by nwamsley1** [vdemichev/DiaNN#1198]
I am applying SILAC modifications to a spectral library using these options: 

--fixed-mod SILAC,0.0,KR,label 
--lib-fixed-mod SILAC 
--channels SILAC,L,KR,0:0; SILAC,H,KR,8.014199:10.008269
--original-mods

Interestingly, in the log I see the following: 

Registered SILAC channel L with following masses: K[0] R[0] 
Registered SILAC channel H with following masses: K[8.0142] R[10.0083] 
Registered SILAC channel decoy with following masses: K[16.0284] R[20.0165] 

What are the channel decoys? Is this an additional set of decoys which have the same sequence as the targets, but a different mass offset for the labeled amino acids? So then there would be two decoys for each target, one shuffled and one labeled "extra" heavy. 

I assume this is to avoid falsely attributing labeled library peptides to spectra produced by unlabeled peptides and vice-versa. For example if I searched an unlabeled sample with labeled sequences added to the library I would probably identify heavy labeled peptides at a rate higher than my FDR threshold? But with these additional decoys, maybe there is no such problem?

Thanks!

**Comment by vdemichev** [comment]
Hi,

A 'decoy' channel contains in silico generated precursor ions with the label masses as DIA-NN specifies in the log. Since any peptide-spectrum match in this channel is known to be false, it allows to estimate the numbers of precursors with false channel assignment in the other channels, and hence calculate channel q-values. These channel decoys do not participate in the calculation of the regular FDR, i.e. this is purely for evaluating channel confidence.

> But with these additional decoys, maybe there is no such problem?

Exactly!

Best,
Vadim
