### ISSUE TITLE
Use DIA-NN v.1.8 to convert from MSP to TSV

### ISSUE THREAD

**Issue by MarcIsak** [vdemichev/DiaNN#205]
Hi, 

I'd like to use a chromatogram library (generated in EncyclopeDIA v.1.2.2 from some GPF runs) to analyze my DIA runs in DIA-NN 1.8. I converted the library in EncyclopeDIA from ELIB-format to MSP format. Then I decided to use DIA-NN to convert the chromatogram library from MSP format to TSV (I'd like to be able to read the library info in R, while making sure that the library can be used in DIA-NN). However, when I look at the TR_recalibrated column in the generated TSV-library, I noticed that the only value was **0**, meaning that the library lacks RT information.

I just wonder if you have any clues on how I can go about generating this chromatogram library so that it will work properly in DIA-NN? 

Best,

Marc

**Comment by vdemichev** [comment]
Hi Marc,

Sorry, .msp support is experimental, apparently when converted from EncyclopeDIA RTs are not read by DIA-NN correctly.

In general, we strongly recommend to use DIA-NN itself and not third-party software when creating spectral libraries from any kind of DIA data. Because of library quality, not just format compatibility.

Best,
Vadim

**Comment by MarcIsak** [comment]
Update: I managed to populate the TR_recalibrated column if I first converted the ELIB-format to OpenSwath TSV in EncyclopeDIA, and then in DIA-NN from OpenSwath TSV to DIA-NN TSV. But I guess it should be possible to go from MSP to DIA-NN TSV without losing the RT info
