### ISSUE TITLE
0 precursors added to the library

### ISSUE THREAD

**Issue by Allen188** [vdemichev/DiaNN#25]
I want to generate a library with DIANN(1.7.4) libfree on linux. But there are two problems.1： Many DIA files indicate that ’Cannot perform a mass calibration, too few rarely identify precursors‘ ; 2： According to your method, I ran on many computers, and finally recalculated the .quant file. There are 237 files, but all hint '0 precursors added to the library', the generated library file is empty, but the quantitative result is successful. I selected two files to test and the test results were successful.

/soft/diann-linux-1.7.4  --f A20181013sunyt_shaoyk_CRCA_DIA_Rp_b3_10.mzML    --f A20181114sunyt_shaoyk_CRCA_DIA_b13_9.mzML  --lib "" --threads 24 --verbose 1 --out "reportsum.tsv" --out-gene "reportsum.genes.tsv" --qvalue 0.01 --temp "./" --out-lib "libsum.tsv" --gen-spec-lib --fasta "swissprot_human_20180209_target_IRT_contaminant.fasta" --fasta-search --min-fr-mz 100 --max-fr-mz 1500 --met-excision --cut-after KR --missed-cleavages 2 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 400 --max-pr-mz 1200 --unimod4 --var-mods 1 --unimod35 --use-quant --rt-profiling --pg-level 1 

I deleted a lot of suspicious files, and as I built the library, less and less of this stuff was added to it, until after a few dozen files it was 0
![image](https://user-images.githubusercontent.com/50605360/77152934-d73d8b80-6ad3-11ea-9c86-1f84faf5bb7f.png)
![image](https://user-images.githubusercontent.com/50605360/77152978-e58ba780-6ad3-11ea-8a23-5ff57558d73e.png)

**Comment by vdemichev** [comment]
Hi Allen188,

The "cannot perform mass calibration" message is displayed when the number of identifications is very low. Likewise, 0 precursors would be added to the spectral library if (i) no precursors that have been identified have spectra which are of high enough quality (only high quality spectra are saved to the library) or (ii) all the precursors identified got higher scores in other runs of the experiment.

In your case the low number of identifications is caused by
- old DIA-NN version was used; DIA-NN 1.7.9 is significantly better when it comes to library-free search because it uses deep learning-based prediction of peptide spectra & retention times; deep-learning for now works under Windows only though;
- no training library (can be specified with the --learn-lib command) - it's very important to use a training library with old DIA-NN versions; training library should NOT be used with DIA-NN 1.7.9 though (unless there's a very specific reason for using it, which is not the case here);
- the number of missed cleavages increased to 2 - this causes significant expansion of the search space, which in this case lowers the identification numbers; allowing for two missed cleavages is only useful when there are lots of IDs with 1 missed cleavage already and one is specifically interested in quantifying peptides with 2 missed cleavages (very rarely the case);
- methionine oxidation was allowed as a variable modification - again, this leads to search space expansion, negative effect on identification numbers;
- using "--mass-acc-cal 30" or even lower value might help perform calibration properly; also a good idea to tell DIA-NN which mass accuracy value to use (e.g. --mass-acc 20 --mass-acc-ms1 12 for SCIEX TOF instruments) - if DIA-NN cannot identify a reasonable number of peptides, it will not be able to optimise the mass accuracy properly; 
- fragment mass range was changed to 100 m/z - 1500 m/z - better try with the default one first;
- RT profiling is not very useful in general and does not help spectral library generation at all  - please turn it off, this will speed up the search considerably.

Changing the settings as described above and using a newer DIA-NN version should yield a good number of ID numbers and make the analysis at least several times faster.

I would also think it might be helpful to try the analysis first on several files under Windows - it's much easier to configure things and save logs using the GUI. Plus this allows to use deep learning-based spectra/RTs prediction on DIA-NN 1.7.9. I know several colleagues that run DIA-NN on Windows using a virtual machine on Linux. Although a Linux cluster might be useful for running large-scale automated experiments, generating spectral libraries only requires a low number of runs, so can be easily done on any single machine.

Please also consider using a large human spectral library (e.g. ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls) instead of library-free search. Analysing your runs with such a library would allow to 'refine' spectra and retention times, thus producing a project-specific library.

Hope this helps! Please let me know if suggestions above work. Please don't hesitate to contact me if something does not :) We can also have a Skype call to discuss DIA-NN settings if you wish.

Best wishes,

Vadim

**Comment by Allen188** [comment]
Hi, Vdemichev, thanks for the quick response. I took your advice and used the 1.7.9 GUI version, but it was too slow and has not yet worked out.I tried linux1.7.4 again and listened to your suggestion, but the library result was still 0, and the precursion was less and less. It seems that the precursion found in each file is not union but intersection.Operating parameters are as follows:

 --lib "" --threads 24 --verbose 1 --out "reportsum.tsv" --out-gene "reportsum.genes.tsv" --qvalue 0.01 --temp "./" --out-lib "libsum.tsv" --gen-spec-lib --fasta "swissprot_human_20180209_target_IRT_contaminant.fasta" --fasta-search --min-fr-mz 100 --max-fr-mz 1500 --met-excision --cut-after KR --missed-cleavages 2 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 400 --max-pr-mz 1200 --unimod4 --var-mods 1 --unimod35  --window 24 --mass-acc 30.0 --mass-acc-ms1 20 --individual-mass-acc --use-quant --pg-level 1 

![image](https://user-images.githubusercontent.com/50605360/77287359-57503500-6d10-11ea-9c09-846a0380d3da.png)
![image](https://user-images.githubusercontent.com/50605360/77287388-67681480-6d10-11ea-9446-0c078ed1cac2.png)

**Comment by vdemichev** [comment]
Hi Allen188,

It's unsurprising that it does not work well with these parameters. As I mentioned above, --missed-cleavages 2 and --var-mods 1 --unimod35 do decrease identification numbers, if these are low already. Also, --window 24 is a bit strange, I have never seen a DIA run for which that would make sense. And without a training library or (even better) deep learning-based spectra & RTs prediction (which works under Windows only) library-free search is not expected to perform well anyway.

I am a bit confused, why you say it is not working now? On the screenshots you've attached, DIA-NN does add 809 precursors to the library based on identifications in one of the runs. The fact that for some runs it's 0 is expected. What it means is that all precursors identified in these runs had even higher scores in other runs. 

It's difficult for me to say anything more concrete about the data right now. May I ask you to please analyse these runs (maybe one or several of them) under Windows (using the DIA-NN GUI), with the spectral library (if you runs were obtained from a human cell line lysate, please use ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls)? Please use "Log level 3 - only this would give sufficiently detailed outptut". Could you then please save the entire log using the "Save log" button and send it to me?

If it is inconvenient to run it on Windows, Linux would also do: please use the "--verbose 3" command and direct the entire output to a file (for example, as described here https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file).

In general, I would always recommend to optimise the workflow (if the default settings arenot suitable for some reason) under Windows, using the GUI, and only then use the optimised settings under Linux for large scale automated processing. 

Hope this helps! Please don't hesitate to contact me if something is not working as expected. 

Best wishes,

Vadim

**Comment by vdemichev** [comment]
Btw, what type of samples are these runs? If it's, say, blood plasma, then library-free mode without deep learning is expected to fail

**Comment by Allen188** [comment]
Hi, Vdemichev
Because my DDA library is too small, I want to use diann library free to identify the extra precursor, so I just want to use fasta search, there is no training library. But no matter how much I try, the final merge after the. quant file, the precursors added to the library is always less and less, the exported library is very small in the end, as shown in the picture, the first file has 3616 precursors, the last file has 5 precursors, the last output library has only 5 precursors. And I'm dealing with human tissue samples. 
The other thing I do is use multiple Linux machines to generate.quant, and then use one Linux machine to merge all the results with the following code.It is worth mentioning that DIA quantitative results are not a problem, is there is a problem in the library

/soft/diann-linux-1.7.9 --f ...mzML --lib "" --threads 24 --verbose 3 --out "test26.tsv" --out-gene "test26.genes.tsv" --qvalue 0.01 --temp "./" --out-lib "test26.tsv" --gen-spec-lib --fasta "swissprot_human_20180209_target_IRT_contaminant.fasta" --fasta-search --min-fr-mz 100 --max-fr-mz 1500 --met-excision --cut-after KR --min-pep-len 7 --max-pep-len 30 --min-pr-mz 400 --max-pr-mz 1200 --unimod4 --mass-acc 30.0 --mass-acc-ms1 20 --individual-windows --individual-mass-acc --use-quant --pg-level 1   
![image](https://user-images.githubusercontent.com/50605360/77604631-f57d0e80-6f4d-11ea-9993-d081eb7f344f.png)

**Comment by Allen188** [comment]
I found that a single file can successfully export spec-library. For example, I have 100 DIA running on different computers. Can I directly merge the library.tsv files and remove duplicates

**Comment by vdemichev** [comment]
Hi Allen188,

Many thanks for your patience in troubleshooting this! I know it's often very frustrating when the software does not seem to work as expected.

> Because my DDA library is too small, I want to use diann library free to identify the extra precursor

Please try ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls. This is a very large human cell lysate library with > 400'000 precursors. Note that you can refine spectra and RTs in this library using DIA-NN based on your runs (the same way you are doing with library-free search). It will probably be 1-2 orders of magnitude faster and will yield much better resutls.

I would also like to note that if your runs are replicate injections or just very similar samples, there's no need to make a spectral library from all of them, 3-10 would be more than enough. Furthermore, if this is the case (i.e. your runs are not gas-phase fractionation runs), it's very unlikely that the resulting spectral library would be better than the large public library by the link above. I would then suggest analysing all your runs with that pubic library and then filtering that library for precursors that are relatively consistently detectable in your runs. I am 90% confident that this will be the best possible approach in your case.

> so I just want to use fasta search, there is no training library

Training library is exactly designed for FASTA search, so please do use it, if you don't want to use deep learning spectra/RTs prediction. With training library it is much better than without it. The search is at least several times faster (and for some samples might be over an order of magnitude faster). Please note that it's irrelevant what kind of sample the training library was created from. You can, for example, use training_lib.tsv from the "SuppFig 10.1 - gas-phase fractionation" folder here https://osf.io/6g3ux/files/. Can just download it and give DIA-NN the "--learn-lib training_lib.tsv" command (without quotes).

However with deep learning it is much better than with training library. Basically, analysing multiple runs on a single Windows machine with deep learning might be actually faster than using a powerful Linux cluster without deep learning and training library. 

> But no matter how much I try, the final merge after the. quant file, the precursors added to the library is always less and less, the exported library is very small in the end, as shown in the picture, the first file has 3616 precursors, the last file has 5 precursors, the last output library has only 5 precursors.

Thank you very much for reporting this. You are right, what you've shown on the screenshots is definitely not the intended behaviour. I will look at the DIA-NN code and try to see how it might happen that only precursors from the last run get saved to the library. However this might be caused by two things: (i) there was some problem with .quant files being moved between machines, i.e. they might have been acquired with settings different from the ones used when generating the library; this then makes DIA-NN behave in such a strange way; or, alternatively, (ii) there's a bug in DIA-NN which manifests specifically with your runs (I just tried and was not able to reproduce this). It's definitely worth trying to do the whole analysis on a single machine without moving the .quant files, preferably using deep learning under Windows, or (if this is impossible) a training library.

 > I found that a single file can successfully export spec-library. For example, I have 100 DIA running on different computers. Can I directly merge the library.tsv files and remove duplicates

Yes, you can merge the libraries, for example, using R. Just choose for each precursor a single run with the best q-value. However what you can also do is take all peptides identified by DIA-NN with a specified confidence level in your runs (based on the regular report, not the spectral library) and make an in silico library from them using deep learning under Windows.

Best wishes,

Vadim

**Comment by Ellen1101** [comment]
> Hi Allen188,
> 
> It's unsurprising that it does not work well with these parameters. As I mentioned above, --missed-cleavages 2 and --var-mods 1 --unimod35 do decrease identification numbers, if these are low already. Also, --window 24 is a bit strange, I have never seen a DIA run for which that would make sense. And without a training library or (even better) deep learning-based spectra & RTs prediction (which works under Windows only) library-free search is not expected to perform well anyway.
> 
> I am a bit confused, why you say it is not working now? On the screenshots you've attached, DIA-NN does add 809 precursors to the library based on identifications in one of the runs. The fact that for some runs it's 0 is expected. What it means is that all precursors identified in these runs had even higher scores in other runs.
> 
> It's difficult for me to say anything more concrete about the data right now. May I ask you to please analyse these runs (maybe one or several of them) under Windows (using the DIA-NN GUI), with the spectral library (if you runs were obtained from a human cell line lysate, please use ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls)? Please use "Log level 3 - only this would give sufficiently detailed outptut". Could you then please save the entire log using the "Save log" button and send it to me?
> 
> If it is inconvenient to run it on Windows, Linux would also do: please use the "--verbose 3" command and direct the entire output to a file (for example, as described here https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file).
> 
> In general, I would always recommend to optimise the workflow (if the default settings arenot suitable for some reason) under Windows, using the GUI, and only then use the optimised settings under Linux for large scale automated processing.
> 
> Hope this helps! Please don't hesitate to contact me if something is not working as expected.
> 
> Best wishes,
> 
> Vadim

Hi Vadim,

Does the Linux version still not support the function of "Deep learning-based generation of high quality spectral libraries _in silico_ (Windows only)" ? 

I have tried to use the deep learning-based prediction library-free search with 12 DIA raw files, but the output of *.speclib.tsv only contains 3300 spectrums. This is such a small library. 
And this analysis took nearly two days. I wonder are the number of 3300 spectrums and the time reasonable? 
So, I want to try this analysis on Linux using more DIA files. Do you have any suggestions?

Looking forward to your reply.
Chunhui

**Comment by vdemichev** [comment]
Hi Chunhui,

Yes, deep learning is not supported in Linux. There are both licensing and technical reasons for this. I don't think it's a significant problem, as one can make a predicted library on Windows (such a library is always saved automatically when running deep learning-based spectra/RTs prediction) and then use it on Linux. So basically you only need to carry out prediction itself on Windows, while the analysis of any number of DIA runs with the predicted library can be performed on Linux. 

3300 precursors is not a reasonable number for human cell/tissue lysates. 2 days also sounds like a lot, typically that might be the case if DIA-NN struggles to find enough precursors in the data and this slows things down. Using more DIA files is unlikely to improve precursor numbers (basically, worth trying analysing a single file first, and if it does not work well, there's no point in adding more runs). 

In general, spectral libraries should ideally be created from gas-phase fractionation runs. Creating from full precursor range injections will also work fairly well, if either (i) these are super high quality (e.g. 6 hours-gradient runs with uPAC column Biognosys published recently) or (ii) they are from a lower-complexity sample, e.g. yeast lysate. But this would still be inferior to using gas-phase fractionation. 

In summary, library-free search on regular runs should only be used if there is just no better way to create a library. And if available public libraries show suboptimal performance. If you are dealing with human samples, there are typically lots of fairly good public libraries available. For example, ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls, which I mentioned above. Trying a public library is quick, and, most importantly, it will immediately tell you how good the data files themselves are. Also, when run with Log level = 3 (--verbose 3), this might give a hint on how to speed up DIA-NN analysis of these files in other modes, e.g. whether it's OK to set --mass-acc-cal to 30 or even 20, what settings to use for --mass-acc and --mass-acc-ms1, what --window setting to use, etc. 

Hope this helps. If something does not work, please don't hesitate to let me know. Sharing a full analysis log taken at Log level = 3 (--verbose 3) would also be very helpful for me to see what's really going on with these runs. Do I understand correctly that you've developed the PulseDIA method? If you wish, we can have a Skype call to discuss DIA-NN settings & analysis modes.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
P.S. In a number of cases I did get somewhat better results with library-free analysis of full precursor range human samples than with any of the available public libraries. But that was with 90 min+ gradients and well-digested cell lysates.

**Comment by vdemichev** [comment]
Just wonder, any update? Have you managed to make DIA-NN work well on these samples?
