### ISSUE TITLE
support of ion mobiltiy (FAIMS or DIA-PASEF)?

### ISSUE THREAD

**Issue by uohmayer** [vdemichev/DiaNN#27]
Dear Vadim,

I have a quick question regarding the compatibility of DIA raw files that contain ion mobility information (e.g. acquired on a Bruker TIMS TOF pro system using DIA PASEF technology or on an Thermo Exploris 480 system using the FAIMS device). Does DIA-NN currently support these files or do you have any plans to implement the support of this kind of files in the future? 

For the analysis of our "regular" DIA files (acquired on a QExactive HF-X) DIA-NN is a great tool we're about to explore more and more and we highly appreciate its performance and the great  contribution you've made for the whole community.  Thank you very much, best wishes, Uli

**Comment by vdemichev** [comment]
Dear Uli,

Thank you for your interest in DIA-NN!

FAIMS without differential ion selection is fully supported (because on the data level it does not change anything). For example, DIA-NN can analyse the runs from https://www.mcponline.org/content/early/2020/02/12/mcp.TIR119.001906. 

There's alpha-stage support for diaPASEF, which currently has a number of limitations:
- ion mobility information is simply not used; because of this identification numbers and quantification performance are worse than they could be;
- acquisition schemes with window overlap in either ion mobility or m/z dimension are not processed correctly, resulting in worse performance;
- speed has not been optimised properly, so it's not as fast as it would be with regular DIA/SWATH runs.

To analyse diaPASEF runs, remove the file extension filter in the "Add raw files" dialog in DIA-NN GUI (i.e. select "All files") and then select the analysis.tdf file within the sample folder. But please don't expect excellent performance right away - I am in contact with Bruker about this, and diaPASEF implementation in DIA-NN as well as acquisition scheme support will be improved significantly. 

Best wishes,

Vadim
