### ISSUE TITLE
Can't create a report from C:/

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#29]
Hi，
I‘m trying to use DIA-NN for cope with my DIA data.
I have tried the demo data in the GitHub and followed the instructions here.But the text for running prompts that it cannot create a report file in C:/.And today I try to analyse other DIA data.The same error occured and is shown as follows.
![image](https://user-images.githubusercontent.com/50875585/80862473-08e76c00-8ca8-11ea-9266-da9029488872.png)
Could you help me check it out?Thanks a million.
Best regards,
Clover

**Comment by jiangnana01** [comment]
The settings for this running is shown as follows.
![image](https://user-images.githubusercontent.com/50875585/80862601-e0ac3d00-8ca8-11ea-8780-6e7394d3ffb1.png)

**Comment by vdemichev** [comment]
Hi Clover,

This probably happens because that folder is write-protected. Windows has somewhat stupid permission system. Please just create a folder yourself (don't try to save to Program Files created by the system) and instruct DIA-NN to save to that folder.

I also see that the .raw files are not loaded correctly. Has the Thermo MSFileReader been installed? Is this the exact version specified in DIA-NN manual? Also, are these .raw files MSX? MSX acquisition is not supported by DIA-NN.

Best wishes,

Vadim

**Comment by Clovernana** [comment]
Hi Vidim,


Thanks so much for your instructions.I have installed the MS file reader.And I'll try it. 


Best wishes,


Clover


On 5/2/2020 19:20，Vadim Demichev<notifications@github.com> wrote：

Hi Clover,

This probably happens because that folder is write-protected. Windows has somewhat stupid permission system. Please just create a folder yourself (don't try to save to Program Files created by the system) and instruct DIA-NN to save to that folder.

I also see that the .raw files are not loaded correctly. Has the Thermo MSFileReader been installed? Is this the exact version specified in DIA-NN manual? Also, are these .raw files MSX? MSX acquisition is not supported by DIA-NN.

Best wishes,

Vadim
