### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by andyzim111** [vdemichev/DiaNN#38]
When there are two tabs (two pipelines running) and the output folder is the same, DiaNN seems to write the result files that are finished first, and the other pipeline results will not be written.

**Comment by vdemichev** [comment]
What do you mean by the same output folder? Can you please share screenshots and/or logs of both tabs? What you describe will happen if one were to process the same .raw file with the same Temp folder specified - this will cause incorrect output for both pipelines.

**Comment by andyzim111** [comment]
When two pipelines are running and they process the same raw files,  the main output folder is the same for two pipelines. I did not specify the Temp folder. 
When I reproduced the bug, I will show you screenshot and logs.

**Comment by vdemichev** [comment]
OK, I see, that's expected, the same .raw files should not be processed this way. This is because DIA-NN creates a .quant file for each processed raw file - this .quant file contains all the identification and quantification information. And these files should stay there unchanged until the final report generation. If two pipelines analyse the same files at the same time, they will keep overwriting the .quant files of each other, and neither will be able to generate a correct report. 

Please specify a separate Temp folder (to which .quant files are saved) for each of the pipelines, and then everything will work :)

**Comment by andyzim111** [comment]
OK. I got it.
Thanks for quick response.
