### ISSUE TITLE
Precursor.normalised = 0 with Q.Value < 1%

### ISSUE THREAD

**Issue by tuvanasatar** [vdemichev/DiaNN#40]
Hi Vadim,

I noticed that in my dataset processed with DiaNN, for some precursors there is a very small Q.Value (< 1%), but with a precursor quantity Precursor.normalised (and/or Precursor.Quantity) equal to 0. With such low q-values, I would expect high precursor quantities, corresponding to a good quantification, so I'm confused about this 0 value. 
This does not happen often, but I can still flag around 1000 precursors in this case. 
Could you help me understand these cases?

Thank you in advance.

Best regards,
Tuvana

**Comment by vdemichev** [comment]
Hi Tuvana,

Normally, this should happen very rarely (for just few precursors), so for most downstream applications that require the quantities to be log-transformed I would just replace 0 with NA - usually these 0s correspond to misidentifications. 1000 precursors actually sounds quite a lot. If you wish, I can take a look at the respective DIA-NN report, DIA-NN analysis log and the spectral library used.

The 0s occur due to DIA-NN selecting fragments to use for quantifying precursors in a cross-run manner. The 3 selected fragments per precursor can happen not to be detected in some runs (i.e. the precursor got identified using other fragments) - leading to the zero quantity. Most common cause: misidentification. Less common: strong interferences, low precursor quantity in the particular run.

Best wishes,

Vadim

**Comment by tuvanasatar** [comment]
Hi Vadim,

Thank you for your quick answer ! 
Due to confidentiality reasons, I unfortunately don't think I can share the outputs of my DiaNN processing with you. However, I will apply your recommendation to replace the 0s with NA. 

Thanks a lot for your help,
Best regards,
Tuvana
