### ISSUE TITLE
Calculation of protein level FDR starting from report.tsv

### ISSUE THREAD

**Issue by markcelo** [vdemichev/DiaNN#49]
Dear Vadim,  many thanks for DiaNN which has really opened a new chapter for DIA processing. 

I would like to ask you some guidance on how to calculate protein level FDR using DiaNN PSM scores from targets and decoys: 
-	Firstly,  I assume that the two scores columns plus the peptide sequence is all you need for this calculation . Please let me know otherwise.
-	Regarding the actual calculation, how are PSMs aggregated , eg choice of aggregation method, perhaps PSM selection ?  If there is a reference you followed closely maybe that would be an easy way forward. 

-	Lastly, is there a simple way to deduce the sequence of the decoy peptides ? software like percolator needs target and decoy sequences , but they dont seem essential if you have the scores. 

Many thanks !

**Comment by vdemichev** [comment]
Hi Marcelo,

Unfortunately, it's currently impossible to directly calculate protein FDR from target & decoy scores in the report, as done by DIA-NN itself. The reason is, only target peptides identified at particular FDR (and even at 100% FDR that might not be all targets) are reported, along with corresponding decoys. So part of the decoy information is missing. This can be corrected for though, I guess. Can also try inferring protein FDR using the number of target peptides identified for a particular protein, in comparison to the number of target peptides for this protein in the library.

Btw, why would you like to calculate protein FDR manually? DIA-NN does it, and the algorithm has been improved significantly in the development version. SO the next version will be considerably better in this.

In the current DIA-NN version the protein 'score' is taken to be the maximum of PSM scores (CScore column). This will be changed in the next version.

Decoys are generated via GAVLIFMPWSCTYHKRQEND to LLLVVLLLLTSSSSLLNDQE mutation pattern for residues adjacent to the peptide termini. If any of this residues is modified DIA-NN tries to mutate an adjacent residue farthest from the terminus, and if that one is modified too, then the terminal residue. And if the terminal is modified, then the initial residue is mutated, regardless of the presence of a modification. Examples:
PEPTIDE -> PDPTIEE
PC(cam)PTIDE -> PC(cam)LTIEE
PC(cam)M(ox)TIDE -> LC(cam)M(ox)TIEE
(acetyl)PC(cam)M(ox)TIDE -> (acetyl)PS(cam)M(ox)TIDE

Best wishes,

Vadim

**Comment by markcelo** [comment]
Thanks for quick reply Vadim, 

Starting from your question, the reason to re-do protein FDR is simply that we re-did inference towards an Idpicker/Spectronaut style, with the goal of guaranteeing proteins in single protein groups. 

If I got it right, the key issue for protein FDR re-calculation is that not even under 100% FDR you can (currently?) output all targets **and neither** all decoys. In that case, what explains the loss of input peptides/precursors? perhaps  some initial filtering on sequences, or some technicality behind spectrum simulation ? is it safe to assume that such discarded precursors are necessarily at bottom quality among observed scores?

Appreciated the clear randomisation example! It confirms that no inversion is applied , so far.

Best wishes
MArcelo

**Comment by vdemichev** [comment]
HI Marcelo,

It's possible to output everything, it's just not being done. What happens, is that all targets that have been matched to spectra with reasonable confidence are reported, but not all decoys (as each decoy is matched to its respective target and reported with it).

Yes, you can force DIA-NN to use pseudo-inverse decoys (--reverse-decoys), but the way decoys are generated by default is better.

Vadim

**Comment by markcelo** [comment]
Sorry Vadim, 
An obvious detail I did not ask is whether you will modify the program to output the full list of entries needed to calculate protein FDR accurately ? 

Marcelo

**Comment by vdemichev** [comment]
Hi Marcelo,

It's possible to do that, but probably not in the next version.

Vadim

**Comment by cjhjhj** [comment]
Hi Vadim,
Could you please explain a rationale behind the decoy generation (i.e., mutation) rule? I just wonder why you used such a mutation.
Thank you.
