### ISSUE TITLE
Use only proteotypic peptides for quantification?

### ISSUE THREAD

**Issue by jessegmeyerlab** [vdemichev/DiaNN#565]
I am wondering if DIA-NN uses only peptides that are unique to their assigned group for quantification of that group? For example, we are working with data from muscle where myosin heavy isoforms have high sequence overlap. We want to make sure that peptides which are shared across all the myosins are not used for quantification of any isoform.

**Comment by vdemichev** [comment]
For Genes.MaxLFQ.Unique - yes. Otherwise, all assigned to the group precursors are used. A custom selection of peptides for quantification is possible if using the 'iq' or 'diann' R package for MaxLFQ, on the basis of precursor quantities reported by DIA-NN.

**Comment by jossmi** [comment]
I have a follow-up question: In the methods section of the DIA-NN paper, it says:
"A ‘top 3’ method is eventually used for protein quantification: intensities of protein groups are calculated as sums of the intensities of the three most abundant precursors identified with a q-value lower than a given threshold in a particular acquisition."

When you said "Otherwise, all assigned to the group precursors are used.", do you mean "all [of the top three] assigned...precursors", or do you mean that all precursors for the protein group, including those outside of the top three precursors (e.g., ranks 4 through n), are used?

**Comment by vdemichev** [comment]
That's the old DIA-NN version. Now it's MaxLFQ, which uses all precursors.
