### ISSUE TITLE
Qantification

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#61]
Hi,Vadim
I have noticed that DIANN adpots top N method(N=1 by default) for basic quantifacation(including protein or genes level).it looks like  that DIANN extracts the maximum precursor intensity across different runs for the same peptide.And matched to protein level or gene level.Right?And what's the gene group intensity mean？
![image](https://user-images.githubusercontent.com/50875585/95804268-c33dcd80-0d34-11eb-8424-850d7b7e7889.png)
![image](https://user-images.githubusercontent.com/50875585/95804273-c9cc4500-0d34-11eb-8e7e-ff0fc7628eda.png)
https://github.com/vdemichev/diann-rpackage
In this diann R package,for the peptide without modification, it takes the maximum of the respective precursor quantities.So it takes  the maximum value two times for the peptide quantification.And the question is the accuracy for quantification at peptide level.MaxLFQ algorithm is also adopted for peptide/protein/gene level quantification.So it means that MaxLFQ is more accurate in quantification,Right?
And another question,the difference between the precursor and peptide is the charge.So I guess that for the quantification of peptide,the sum of precursor intensities (2+,3+...) should be calculated.And I don't know for sure.
If I have diluted sample (500ng,100ng,20ng,10ng,4ng,here is the injection amount for LC-MS/MS)for lable free quantifacation ,I want to compare the quantification for different imputs. which is more accurate  for quantification comparasion?(precursor level ,peptide level ,protein groups level?I guess the precursor level is the most accurate.Of course ,no normalization across runs.)

**Comment by vdemichev** [comment]
Hi Clover,

Not really, top 1 quantification uses different peptides for different runs.
In general, I strongly recommend using MaxLFQ instead of top 1. "Gene group" refers to the sets of genes in the "Genes' column of the report.

The diann R package can do a number of things, the examples provided are there to just illustrate how to use it.
Yes, MaxLFQ is a lot better.

No, to quantify peptides summing precursor intensities is a bad idea, because when one of the charge states is not identified at FDR < 1% (or whatever threshold you set), this might then grossly affect the quantity. 

If you are interested in proteins, please use MaxLFQ protein quantities (these are also typically a lot less noisy than precursor quantities). If in peptides - calculate MaxLFQ peptide quantities. If in precursors - use Precursor.Normalised or Precursor.Quantity, depending on whether the normalisation as described in DIA-NN is expected to work well with your experiment.

Vadim

**Comment by Clovernana** [comment]
OK,thanks.
