### ISSUE TITLE
Missing ID for +5 and +6 peptides even with precursor range set as 2 - 6

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#918]
Hi,

I have a question regarding the precursor range in DIA-NN. We have a GluC data processed by DIA-NN using the built-in function for a predicted library from FASTA. I set the precursor range 2-6 but there is no peptide identified > 4+ charge state. From GluC enzyme we do expect quite a few +5 or +6 peptides and we also confirmed by Skyline that +5 peptides are there. 

Is it possible that somehow DIA-NN accidentally removed peptide ions > +4 or they were not even searched as all?

**Comment by vdemichev** [comment]
Yes, I think prediction is limited to charge state 4 - this is because the predictor will not work well for higher charge states as it was not trained for those. I am a bit cofnused, what's the chemistry explanation for higher charge states for GluC? I would think it should be the opposite, lower charges with GluC than trypsin?

**Comment by cctsou** [comment]
@vdemichev : Thank you for the response. Indeed it's the limitation of the prediction model, if I feed a spectral library with 5+, 6+ peptide ions then it works fine for me. GluC cuts only E but not D and perhaps that's the reason we have seen longer peptides in our samples thus more peptides show up in 5+ and 6+.
